#!/usr/bin/env python3
"""Aggregate A/B/C/D metrics, select a trade-off optimum, and prepare Priority 2."""

from __future__ import annotations

import argparse
import csv
import io
import json
import time
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
RESULTS_ROOT = ROOT / "results" / "overcorrection"
OUTPUT_CSV = RESULTS_ROOT / "priority1_metrics.csv"
OUTPUT_JSON = RESULTS_ROOT / "priority1_summary.json"
BEST_CONFIG = ROOT / "configs" / "overcorrection_best_projector_only.yaml"
SETTINGS = ("A", "B", "C", "D")


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{time.time_ns()}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def read_metrics(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing evaluation metrics: {path}. Finish Priority 1 evaluation first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def flatten(metrics: dict[str, Any]) -> dict[str, Any]:
    normal = metrics["normal"]
    error = metrics["error"]
    overall = metrics["overall"]
    return {
        "setting": metrics["setting"],
        "train_mode": metrics["train_mode"],
        "error_sampling_ratio": metrics["error_sampling_ratio"],
        "normal_cer": normal["corpus_cer"],
        "error_cer": error["corpus_cer"],
        "overall_cer": overall["corpus_cer"],
        "overcorrection_rate": error["over_correction_rate"],
        "error_preservation_rate": error["error_preservation_rate"],
        "normal_preservation_rate": normal["normal_preservation_rate"],
        "normal_sample_count": normal["sample_count"],
        "error_sample_count": error["sample_count"],
    }


def tradeoff_score(row: dict[str, Any]) -> float:
    """Equal-weight badness score across OCR and preservation objectives."""

    return (
        float(row["overall_cer"])
        + float(row["overcorrection_rate"])
        + (1.0 - float(row["error_preservation_rate"]))
        + (1.0 - float(row["normal_preservation_rate"]))
    )


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fields = [
        "setting",
        "error_sampling_ratio",
        "normal_cer",
        "error_cer",
        "overall_cer",
        "overcorrection_rate",
        "error_preservation_rate",
        "normal_preservation_rate",
        "tradeoff_score",
    ]
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=fields, extrasaction="ignore")
    writer.writeheader()
    writer.writerows(rows)
    atomic_write_text(path, buffer.getvalue())


def write_best_projector_config(best: dict[str, Any], destination: Path) -> None:
    source = ROOT / "configs" / f"overcorrection_{best['setting']}.yaml"
    with source.open(encoding="utf-8") as handle:
        config = yaml.safe_load(handle)
    setting = f"{best['setting']}_projector_only"
    config["setting"] = setting
    config["train_mode"] = "projector_only"
    config["error_sampling_ratio"] = float(best["error_sampling_ratio"])
    config["output_dir"] = f"outputs/overcorrection/{setting}"
    header = (
        "# Generated by scripts/summarize_overcorrection.py from completed "
        "Priority 1 metrics.\n"
        f"# Best Projector+LoRA source setting: {best['setting']}\n"
    )
    atomic_write_text(
        destination,
        header + yaml.safe_dump(config, allow_unicode=True, sort_keys=False),
    )


def priority2_summary(best: dict[str, Any]) -> dict[str, Any] | None:
    projector_setting = f"{best['setting']}_projector_only"
    path = RESULTS_ROOT / projector_setting / "metrics.json"
    if not path.is_file():
        return None
    projector = flatten(read_metrics(path))
    fields = (
        "normal_cer",
        "error_cer",
        "overall_cer",
        "overcorrection_rate",
        "error_preservation_rate",
        "normal_preservation_rate",
    )
    return {
        "projector_only": projector,
        "projector_lora": best,
        "projector_only_minus_projector_lora": {
            field: float(projector[field]) - float(best[field]) for field in fields
        },
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write-best-config",
        type=Path,
        default=BEST_CONFIG,
        help="Write the Priority 2 projector-only config after selecting best A/B/C/D.",
    )
    parser.add_argument(
        "--no-write-best-config",
        action="store_true",
        help="Aggregate metrics without creating the Priority 2 config.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = [
        flatten(read_metrics(RESULTS_ROOT / setting / "metrics.json"))
        for setting in SETTINGS
    ]
    for row in rows:
        if row["normal_sample_count"] != 2_000 or row["error_sample_count"] != 1_825:
            raise RuntimeError(
                f"Setting {row['setting']} is not a full fixed-benchmark evaluation"
            )
        row["tradeoff_score"] = tradeoff_score(row)
    best = min(rows, key=lambda row: (row["tradeoff_score"], row["overall_cer"], row["setting"]))
    write_csv(OUTPUT_CSV, rows)
    destination = args.write_best_config.expanduser().resolve()
    if not args.no_write_best_config:
        write_best_projector_config(best, destination)
    payload = {
        "selection_rule": (
            "minimum equal-weight badness = overall CER + over-correction rate + "
            "(1-error preservation rate) + (1-normal preservation rate); ties use "
            "overall CER then setting name"
        ),
        "settings": rows,
        "best_setting": best["setting"],
        "best_error_sampling_ratio": best["error_sampling_ratio"],
        "best_projector_only_config": str(destination) if not args.no_write_best_config else None,
        "priority2": priority2_summary(best),
    }
    atomic_write_text(
        OUTPUT_JSON,
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
